language: python
os: linux
python:
  - "3.9"
# command to install dependencies
script:
  - black --check .
  - flake8 --exclude=migrations --max-line-length=99 .
  # - python -m coverage run --source=soloconnect manage.py test --keepdb
  # - coverage run --source=soloconnect manage.py test
install:
  - pip install -r requirements.txt

after_success:
  - python -m coveralls

deploy:
  - provider: elasticbeanstalk
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    region: $REGION_UE1
    app: $APP_NAME
    bucket: $BUCKET_NAME_UE1
    env: soloconnect-production
    on:
      branch: master
  - provider: elasticbeanstalk
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    region: $REGION_UE1
    app: $APP_NAME
    bucket: $BUCKET_NAME_UE1
    env: soloconnect-integration
    on:
      branch: develop
  - provider: elasticbeanstalk
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    region: $REGION_UE1
    app: $APP_NAME
    bucket: $BUCKET_NAME_UE1
    env: soloconnect-chat-integration
    on:
      branch: feature-private-chat-1-copy