language: python
os: linux
python:
  - "3.8"
# command to install dependencies
script:
  - black --check .
  - flake8 --exclude=migrations .
  - coverage run --source=soloconnect soloconnect/manage.py test
install:
  - pip install -r soloconnect/requirements.txt

after_script:
  - python -m coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  region: "us-west-2"
  app: "soloconnect"
  env: "soloconnect-integration"
  bucket_name: "elasticbeanstalk-us-west-2-698845801092"
  on:
    branch: develop