branch-defaults:
  default:
    environment: development-env
    group_suffix: null
  feature-initial-deployment:
    environment: development-env
environment-defaults:
  development-env:
    branch: null
    repository: null
global:
  application_name: soloconnect
  branch: null
  default_ec2_keyname: sc-keypair
  default_platform: Python 3.11
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
