# Generated by Django 4.2.7 on 2023-12-10 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0001_initial"),
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="sending_user_image",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_profile.userimages",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="thread",
            name="updated",
            field=models.DateTimeField(),
        ),
    ]
