# Generated by Django 4.2.7 on 2023-12-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_alter_chatmessage_sending_user_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="sending_user_image",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="sending_image_url",
            field=models.CharField(default=""),
        ),
    ]
