# Generated by Django 4.2.7 on 2023-12-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_remove_chatmessage_sending_user_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="receiving_image_url",
            field=models.CharField(default=""),
        ),
    ]
