# Generated by Django 4.2.7 on 2023-12-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_remove_chatmessage_receiving_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="first_user_image_url",
            field=models.CharField(default="/media/default_avatar.png"),
        ),
        migrations.AlterField(
            model_name="thread",
            name="second_user_image_url",
            field=models.CharField(default="/media/default_avatar.png"),
        ),
    ]
