# Generated by Django 4.2.6 on 2023-11-14 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0003_alter_usertrip_travel_type"),
        ("matching", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertripmatches",
            name="u_trip",
        ),
        migrations.AddField(
            model_name="usertripmatches",
            name="receiver_user_trip",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver_trip",
                to="trip.usertrip",
            ),
        ),
        migrations.AddField(
            model_name="usertripmatches",
            name="sender_user_trip",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender_trip",
                to="trip.usertrip",
            ),
        ),
    ]
