# Generated by Django 4.2.6 on 2023-11-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertripmatches",
            name="match_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Cancelled", "Cancelled"),
                    ("Matched", "Matched"),
                    ("Unmatched", "Unmatched"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
