# Generated by Django 4.2.6 on 2023-10-30 17:40

import common
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0002_remove_trip_end_trip_remove_trip_start_trip_usertrip"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertrip",
            name="travel_type",
            field=common.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[("Solo", "Solo"), ("Companion", "Companion")],
                    max_length=30,
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="destination_city",
            field=models.CharField(max_length=500, verbose_name="Destination City"),
        ),
        migrations.AlterField(
            model_name="trip",
            name="destination_country",
            field=models.CharField(max_length=500, verbose_name="Destination Country"),
        ),
        migrations.AlterField(
            model_name="usertrip",
            name="end_trip",
            field=models.DateField(
                help_text="Enter the date you plan to leave your destination",
                verbose_name="Trip End Date",
            ),
        ),
        migrations.AlterField(
            model_name="usertrip",
            name="start_trip",
            field=models.DateField(
                help_text="Enter the date you will arrive at your destination",
                verbose_name="Trip Start Date",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trip",
            unique_together={("destination_country", "destination_city")},
        ),
        migrations.RemoveField(
            model_name="trip",
            name="travel_type",
        ),
    ]
