# Generated by Django 4.2.6 on 2023-11-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0002_usertrip_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertrip",
            name="travel_type",
            field=models.CharField(
                choices=[("Solo", "Solo"), ("Companion", "Companion")], max_length=30
            ),
        ),
    ]
