# Generated by Django 4.2.6 on 2023-11-04 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("trip", "0004_alter_trip_destination_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="destination_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities_light.country",
            ),
        ),
    ]
