# Generated by Django 4.1 on 2023-11-20 20:34

import common
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("dob", models.DateField(null=True, verbose_name="Date of birth")),
                (
                    "bio",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="Bio"
                    ),
                ),
                (
                    "university",
                    models.TextField(
                        max_length=200, null=True, verbose_name="University"
                    ),
                ),
                (
                    "age_lower",
                    models.IntegerField(
                        default=18,
                        help_text="Enter lower bound for age filter",
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(99),
                        ],
                        verbose_name="Age(lower bound)",
                    ),
                ),
                (
                    "age_upper",
                    models.IntegerField(
                        default=99,
                        help_text="Enter upper bound for age filter",
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(99),
                        ],
                        verbose_name="Age(upper bound)",
                    ),
                ),
                (
                    "verified_prof",
                    models.BooleanField(
                        default=False, verbose_name="Verified profiles only?"
                    ),
                ),
                (
                    "drink_pref",
                    models.CharField(
                        choices=[
                            ("Frequently", "Frequently"),
                            ("Socially", "Socially"),
                            ("Rarely", "Rarely"),
                            ("Never", "Never"),
                        ],
                        default="Never",
                        max_length=20,
                        verbose_name="Drinking Preferences",
                    ),
                ),
                (
                    "smoke_pref",
                    models.CharField(
                        choices=[
                            ("Socially", "Socially"),
                            ("Regularly", "Regularly"),
                            ("Never", "Never"),
                        ],
                        default="Never",
                        max_length=20,
                        verbose_name="Smoking Preferences",
                    ),
                ),
                (
                    "edu_level",
                    models.CharField(
                        choices=[
                            ("In college", "In college"),
                            ("Undergraduate degree", "Undergraduate degree"),
                            ("In grad school", "In grad school"),
                            ("Graduate degree", "Graduate degree"),
                        ],
                        default="In college",
                        max_length=30,
                        verbose_name="Education Level",
                    ),
                ),
                (
                    "interests",
                    common.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("hiking", "hiking"),
                                ("clubbing", "clubbing"),
                                ("beach", "beach"),
                                ("sightseeing", "sightseeing"),
                                ("bar hopping", "bar hopping"),
                                ("food tourism", "food tourism"),
                                ("museums", "museums"),
                                (
                                    "historical/cultural sites",
                                    "historical/cultural sites",
                                ),
                                ("spa", "spa"),
                                ("relaxed", "relaxed"),
                                ("camping", "camping"),
                                ("sports", "sports"),
                            ],
                            max_length=50,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "languages",
                    common.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("Chinese", "Chinese"),
                                ("Spanish", "Spanish"),
                                ("English", "English"),
                                ("Arabic", "Arabic"),
                                ("Hindi", "Hindi"),
                                ("Bengali", "Bengali"),
                                ("Portuguese", "Portuguese"),
                                ("Russian", "Russian"),
                                ("Japanese", "Japanese"),
                                ("Urdu", "Urdu"),
                            ],
                            max_length=30,
                        ),
                        default=list,
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="profileImages/")),
                ("uploaded", models.DateTimeField(auto_now_add=True)),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_profile.userprofile",
                    ),
                ),
            ],
        ),
    ]
