# Generated by Django 4.2.6 on 2023-10-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="university",
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
