# Generated by Django 4.2.6 on 2023-10-10 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_customuser_university"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dob", models.DateField()),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("university", models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterModelManagers(
            name="customuser",
            managers=[("objects", user_profile.models.UserManager()),],
        ),
        migrations.RemoveField(model_name="customuser", name="bio",),
        migrations.RemoveField(model_name="customuser", name="dob",),
        migrations.RemoveField(model_name="customuser", name="university",),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.DeleteModel(name="MatchingPreferences",),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
