# Generated by Django 4.2.6 on 2023-10-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0004_alter_userprofile_bio_alter_userprofile_dob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="university",
            field=models.TextField(max_length=200, null=True),
        ),
    ]
